project:
  type: website
  output-dir: docs
  execute-dir: file
  render:
    - "*.qmd"
    - "!template"

comments:
  hypothesis: true

execute:
  freeze: auto

website:
  title: "Intelligence and Its Neural Correlates"
