project:
  type: website
  execute-dir: file
  render:
    - "*.qmd"
    - "!template"

comments:
  hypothesis: true

execute:
  freeze: true

website:
  title: "Intelligence and Its Neural Correlates"
