# we have 20 indicators in total
max_num_vars <- 20
# this file will track the subjects for both neural and behavior data
# currently generated by `project_bench_cpm`
file_subjs_combined <- "data/subjs_combined"

# basic configurations for CPM modeling
config_neural <- tidyr::expand_grid(
  modal = c("nbackfull", "rest", "run1rest"),
  parcel = c("nn268", "Power264"),
  gsr = c("with", "without")
) |>
  dplyr::mutate(
    file = fs::path(
      "data/neural",
      sprintf(
        "FC_modal-%s_parcel-%s_gsr-%s.arrow",
        modal, parcel, gsr
      )
    ),
    tar_neural = paste(
      "file_neural", modal, parcel, gsr,
      sep = "_"
    ) |>
      rlang::syms()
  )
hypers_cpm <- tidyr::expand_grid(
  tibble::tibble(kfolds = 10),
  dplyr::bind_rows(
    tibble::tibble(
      thresh_method = "alpha",
      thresh_level = 0.01
    ),
    tibble::tibble(
      thresh_method = "sparsity",
      thresh_level = 0.01
    )
  )
)

# scales for common features
sexes <- c(M = "Male", F = "Female")
scale_sexes <- list(
  name = "Sex",
  limits = names(sexes),
  labels = sexes
)

parcels <- c(
  nn268 = "Shen268",
  Power264 = "Power264"
)
scale_parcels <- list(
  name = "Parcellation",
  limits = names(parcels),
  labels = parcels
)

thresh_methods <- c(
  alpha = "Alpha",
  sparsity = "Sparsity"
)
scale_thresh_methods <- list(
  name = "Edge Threshold Method",
  limits = names(thresh_methods),
  labels = thresh_methods
)

edge_types <- c(
  all = "Combined",
  neg = "Anti-Corr Networks",
  pos = "Pos-Corr Networks"
)
scale_edge_types <- list(
  name = "Edge Type",
  limits = names(edge_types),
  labels = edge_types
)

modalities <- c(
  run1rest = "Combined",
  nbackfull = "Task",
  rest = "Resting"
)
scale_modalities <- list(
  name = "Modality",
  limits = names(modalities),
  labels = modalities
)

meas_behav <- c(
  g_full = "G-Factor",
  rapm = "RAPM"
)
scale_meas_behv <- list(
  name = "Behavioral Measure",
  limits = names(meas_behav),
  labels = meas_behav
)
