# general ----
# we have 20 indicators in total
max_num_vars <- 20
# this file will track the subjects for both neural and behavior data
# currently generated by `project_bench_cpm`
file_subjs_combined <- "data/subjs_combined"
file_subjs_neural <- "data/subjs_neural"

# basic configurations for CPM modeling ----
config_neural <- tidyr::expand_grid(
  cond = c("nbackrun1", "rest", "run1rest", "latent"),
  parcel = c("nn268", "Power264"),
  filt = "bandpass", # eliminate low-pass
  gsr = c("with", "without")
)
hypers_cpm <- tidyr::expand_grid(
  tibble::tibble(kfolds = 10),
  dplyr::bind_rows(
    tibble::tibble(
      thresh_method = "alpha",
      thresh_level = c(0.05, 0.01, 0.005, 0.001)
    ),
    tibble::tibble(
      thresh_method = "sparsity",
      thresh_level = c(0.01, 0.025, 0.05, 0.1)
    )
  )
)

# scales for parameters ----
# scales for demographic variables
sexes <- c(M = "Male", F = "Female")
scale_sexes <- list(
  name = "Sex",
  limits = names(sexes),
  labels = sexes
)

sites <- c(BJ = "Beijing", CQ = "Chongqing")
scale_sites <- list(
  name = "Site",
  limits = names(sites),
  labels = sites
)

# scales for neural parameters
conds <- c(
  nbackrun1 = "Task",
  rest = "Resting",
  run1rest = "Combined",
  latent = "Latent"
)
scale_conds <- list(
  name = "Task Condition",
  limits = names(conds),
  labels = conds
)
parcels <- c(
  nn268 = "Shen268",
  Power264 = "Power264"
)
scale_parcels <- list(
  name = "Parcellation",
  limits = names(parcels),
  labels = parcels
)
filts <- c(
  bandpass = "Bandpass",
  lowpass = "Lowpass"
)
scale_filts <- list(
  name = "Filtering Method",
  limits = names(filts),
  labels = filts
)
gsrs <- c(
  with = "With GSR",
  without = "Without GSR"
)
scale_gsrs <- list(
  name = "Global Signal Regression",
  limits = names(gsrs),
  labels = gsrs
)

# scales for CPM parameters
thresh_methods <- c(
  alpha = "Alpha",
  sparsity = "Sparsity"
)
scale_thresh_methods <- list(
  name = "Edge Threshold Method",
  limits = names(thresh_methods),
  labels = thresh_methods
)
edge_types <- c(
  all = "Combined Networks",
  pos = "Pos-Corr Networks",
  neg = "Anti-Corr Networks"
)
scale_edge_types <- list(
  name = "Edge Type",
  limits = names(edge_types),
  labels = edge_types
)

# scales for behavioral parameters
meas_behav <- c(
  g_full = "G Overall",
  rapm = "RAPM"
)
scale_meas_behv <- list(
  name = "Behavioral Measure",
  limits = names(meas_behav),
  labels = meas_behav
)

# scales for binarize parameters
binarize_methods <- c(
  value = "Minimal Proportion",
  count = "Top N Edges"
)
scale_binarize_methods <- list(
  name = "Network Binarize Method",
  limits = names(binarize_methods),
  labels = binarize_methods
)

# meta data for targets projects ----
get_store_path <- function(project) {
  here::here() |>
    withr::with_dir(
      targets::tar_config_get("store", project = project)
    ) |>
    here::here()
}
store_preproc_behav <- get_store_path("project_preproc_behav")
store_bench_cpm <- get_store_path("project_bench_cpm")
store_cpm_main <- get_store_path("project_cpm_main")
store_task_selection <- get_store_path("project_task_selection")
store_g_invariance <- get_store_path("project_g_invariance")
